### ISSUE TITLE
Base de datos

### ISSUE THREAD

**Issue by cperales** [guillemborrell/dateaproject#6]
_Lo escribo aquí, no tanto para que lo incluyas @guillemborrell, sino para no olvidarme yo_

Por el problema de la API de Github al superar el límite de peticiones (rate limite), una posible solución sería que guardase localmente, en algún documento (un CSV puede valer), de manera que una vez que no tenga que realizar peticiones siempre que se busque información de los proyectos abandonados.

**Comment by guillemborrell** [comment]
Esta es una aplicación que corre en Google Appengine que contiene una base de datos clave valor: https://cloud.google.com/appengine/docs/python/ndb/. En un futuro los datos generados por los usuarios y proyectos registrados se almacenarán ahí.
