### ISSUE TITLE
¿Sería buena idea un request asíncrono?

### ISSUE THREAD

**Issue by cperales** [guillemborrell/dateaproject#7]
He visto que podría sustituirse el paquete requests for [grequests](https://github.com/kennethreitz/grequests), que permite una petición asíncrona a la api de Github.

La pregunta es, ¿sería útil implementarlo? ¿Serviría de algo? Te pregunto a ti @guillemborrell que sabes más del tema.

**Comment by guillemborrell** [comment]
grequests y requests se llevan regular con GAE para hacer peticiones a la API de GitHub, así que mejor no depender de ellos.
